name = "PkgCite"
uuid = "50d0efc5-baaf-4329-a409-faca2d9bd902"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com>"]
version = "0.1.3"

[deps]
BibParser = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
Bibliography = "f1be7e48-bf82-45af-a471-ae754a193061"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
BibParser = "0.1, 0.2"
Bibliography = "0.2, 0.3"
DataStructures = "0.18"
HTTP = "0.9, 1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
